<?php
/**
 * Created by PhpStorm.
 * User: snark | itfrogs.ru
 * Date: 4/3/18
 * Time: 12:06 PM
 */

return array(
    'https' => array(
        'title' => _wp('HTTPS check'),
        'description' => _wp('If not https, the bot will not work.'),
        'control_type' => waHtmlControl::CUSTOM . ' ' . 'telegramAssistantPlugin::getHttpsCheckControl',
        'subject' => 'basic_settings',
    ),
    'key' => array(
        'value' => '',
        'title' => _wp('Bot token'),
        'description' => _wp('Set the API key.'),
        'control_type' => 'text',
        'subject' => 'basic_settings',
    ),
    'use_socks5' => array(
        'value' => 0,
        'title' => _wp('Use socks5 proxy'),
        'description' => _wp('If enabled, the socks5 proxy will be used.'),
        'control_type' => waHtmlControl::CHECKBOX,
        'subject' => 'basic_settings',
    ),
    'socks5_address' => array(
        'value' => '127.0.0.1',
        'title' => _wp('Socks5 proxy address'),
        'description' => _wp('If empty, the proxy will be disabled.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'basic_settings',
    ),
    'socks5_port' => array(
        'value' => 443,
        'title' => _wp('Socks5 proxy port'),
        'description' => _wp('If empty, the proxy will be disabled.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'basic_settings',
    ),
    'socks5_user' => array(
        'value' => 'anonimous',
        'title' => _wp('Socks5 proxy user'),
        'description' => _wp('If empty, the login and password will not be used.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'basic_settings',
    ),
    'socks5_password' => array(
        'value' => '',
        'title' => _wp('Socks5 proxy password'),
        'description' => _wp('If empty, the password will not be used.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'basic_settings',
    ),
    'content_title' => array(
        'value' => _wp('For text formatting, only the following constructions are possible:'),
        'title' => _wp('Hint'),
        'control_type' => waHtmlControl::HELP,
        'subject' => 'interface_settings',
    ),
    'content_help' => array(
        'value' => '<b>bold</b>, <strong>bold</strong>, <i>italic</i>, <em>italic</em>, <a href="http://www.example.com/">inline URL</a>, <a href="tg://user?id=123456789">inline mention of a user</a>, <code>inline fixed-width code</code>, <pre>pre-formatted fixed-width code block</pre>',
        'control_type' => waHtmlControl::HELP,
        'subject' => 'interface_settings',
    ),
    'welcome' => array(
        'value' => _wp('Welcome!'),
        'title' => _wp('Welcome text'),
        'description' => _wp('The text that appears when you start the bot.'),
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_1_1_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 1)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 1) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_1_1_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 1) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_1_1_action' => array(
        'value' => '/button_1_1',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 1) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_1_1_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 1) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_1_1_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 1) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_1_2_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 2)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 2) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_1_2_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 2) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_1_2_action' => array(
        'value' => '/button_1_2',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 2) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_1_2_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 2) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_1_2_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 2) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_1_3_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 3)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 3) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_1_3_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 3) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_1_3_action' => array(
        'value' => '/button_1_3',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 3) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_1_3_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 3) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_1_3_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 1, '. _wp('column') .' 3) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_1_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 1)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 1) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_1_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 1) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_2_1_action' => array(
        'value' => '/button_2_1',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 1) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_1_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 1) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_2_1_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 1) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_2_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 2)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 2) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_2_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 2) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_2_2_action' => array(
        'value' => '/button_2_2',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 2) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_2_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 2) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_2_2_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 2) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_3_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 3)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 3) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_3_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 3) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_2_3_action' => array(
        'value' => '/button_2_3',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 3) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_2_3_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 3) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_2_3_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 2, '. _wp('column') .' 3) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_1_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 1)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 1) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_1_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 1) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_3_1_action' => array(
        'value' => '/button_3_1',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 1) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_1_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 1) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_3_1_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 1) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_2_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 2)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 2) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_2_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 2) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_3_2_action' => array(
        'value' => '/button_3_2',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 2) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_2_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 2) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_3_2_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 2) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_3_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 3)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 3) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_3_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 3) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_3_3_action' => array(
        'value' => '/button_3_3',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 3) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_3_3_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 3) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_3_3_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 3, '. _wp('column') .' 3) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_1_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 1)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 1) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_1_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 1) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_4_1_action' => array(
        'value' => '/button_4_1',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 1) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_1_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 1) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_4_1_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 1) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_2_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 2)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 2) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_2_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 2) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_4_2_action' => array(
        'value' => '/button_4_2',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 2) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_2_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 2) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_4_2_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 2) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_3_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 3)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 3) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_3_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 3) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_4_3_action' => array(
        'value' => '/button_4_3',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 3) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_4_3_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 3) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_4_3_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 4, '. _wp('column') .' 3) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_1_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 1)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 1) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_1_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 1) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_5_1_action' => array(
        'value' => '/button_5_1',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 1) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_1_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 1) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_5_1_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 1) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_2_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 2)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 2) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_2_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 2) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_5_2_action' => array(
        'value' => '/button_5_2',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 2) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_2_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 2) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_5_2_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 2) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_3_title' => array(
        'value' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 3)',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 3) ' . _wp('title') ,
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_3_type' => array(
        'value' => 'off',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 3) ' . _wp('type') ,
        'control_type' => waHtmlControl::SELECT,
        'options' => array(
            'off'  => _wp('Off'),
            'action'  => _wp('Action'),
            'link'  => _wp('Link'),
            'doc'  => _wp('Document'),
            'photo'  => _wp('Photo'),
            'autio'  => _wp('Audio'),
            'video'  => _wp('Video'),
            'voice'  => _wp('Voice'),
        ),
        'subject' => 'interface_settings',
    ),
    'button_5_3_action' => array(
        'value' => '/button_5_3',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 3) ' . _wp('command') ,
        'description' => _wp('Text command to respond to the button. Be sure to start with "/". For example "/help"'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'button_5_3_content' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 3) ' . _wp('content') ,
        'control_type' => waHtmlControl::TEXTAREA,
        'subject' => 'interface_settings',
    ),
    'button_5_3_path' => array(
        'value' => '',
        'title' => _wp('Button') . ' ' .'('. _wp('row') .' 5, '. _wp('column') .' 3) ' . _wp('path') ,
        'description' => _wp('This field is used only if file transfer is required. The path to the file is specified from the server root. Do not confuse the file path with a link to the file.'),
        'control_type' => waHtmlControl::INPUT,
        'subject' => 'interface_settings',
    ),
    'url' => array(
        'title' => _wp('Bot URL'),
        'description' => _wp('The Internet address on which the bot works.'),
        'control_type' => waHtmlControl::CUSTOM . ' ' . 'telegramAssistantPlugin::getBotUrlControl',
        'subject' => 'info_settings',
    ),
    'webhook' => array(
        'title' => _wp('setWebhook URL'),
        'description' => _wp('Internet address for registering a bot link. If api.telegram.org is blocked for you, use the Tor Browser or other method of bypass blocking to activate the bot.'),
        'control_type' => waHtmlControl::CUSTOM . ' ' . 'telegramAssistantPlugin::getWebhookUrlControl',
        'subject' => 'info_settings',
    ),
    'feedback' => array(
        'title' => _wp('Ask for technical support'),
        'description' => _wp('Click on the link to contact the developer.'),
        'control_type' => waHtmlControl::CUSTOM . ' ' . 'telegramAssistantPlugin::getFeedbackControl',
        'subject' => 'info_settings',
    ),


);